### ISSUE TITLE
Escape Quotes and New Lines

### ISSUE THREAD

**Issue by peterlupu** [mrmans0n/localio#14]
Hi, I'm trying to generate files for my iOS app.
I've noticed that double quotes aren't escaped.
Also, new lines within the translation are untouched, meaning the iOS code has syntax errors.

So I've modified the following in the `ios_writer.rb`

```
translation = term.values[lang].gsub('"', %q(\\\")).gsub("\n", "\\n")
```

Keep in mind that my Ruby knowledge is limited, so I'd like to know if there's a better way to do this, or if there's no actual bug within the gem and my approach is wrong.

Thank you,
Peter

**Comment by mrmans0n** [comment]
The no-escaping is like that by design I'm afraid. I might explore a way to enable some platform specific parsing in the future to allow that, but for now you should use \n in the spreadsheets to be able to keep the strings like that, instead of actually using the new lines. 

Please keep in mind that this gem is intended to be interoperable between a ton of platforms (inputs, like different spreadsheets; and outputs, like ios, android, rails, windows phone, etc), and when two platforms escape in different ways, that's why the except / only methods of the Locfile lets you make different approaches based on something you put in the key. 

But if you want to change it in your local gem, of course, you are welcome to do so! Your code seems correct, so... whatever works for you!! :)
